SELECT NOME AS [NOME DO CLIENTE], ESTADO, [PRIMEIRA COMPRA] 
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [PREÇO DE LISTA] <= 7.00;
/*Caso essa ordenação fosse um valor de texto, ele seguiria a ordem alfabetica*/

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE EMBALAGEM = 'PET';

SELECT * FROM [TABELA DE CLIENTES];

SELECT NOME, [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES] 
WHERE [DATA DE NASCIMENTO] > '1989-12-31';

SELECT NOME, [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES] 
WHERE YEAR ([DATA DE NASCIMENTO]) > '1989';

SELECT NOME, [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES] 
WHERE DAY ([DATA DE NASCIMENTO]) > '10';

SELECT NOME 
FROM [TABELA DE CLIENTES]
WHERE NOME <> 'Erica Carvalho';
/*Eu uso o <> quando eu quero excluir algo
 Ou seja, ela vai retornar desconsiderando todos aqueles que são Erica Carvalho.*/

SELECT NOME, BAIRRO 
FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'Copacabana' OR BAIRRO = 'Tijuca';

SELECT NOME, ESTADO, [PRIMEIRA COMPRA] 
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 0 AND ESTADO = 'SP';

SELECT * FROM [TABELA DE CLIENTES];

SELECT [PERCENTUAL COMISSÃO] 
FROM [TABELA DE VENDEDORES]
WHERE [PERCENTUAL COMISSÃO] <= 8; 

SELECT TAMANHO, [PREÇO DE LISTA] 
FROM [TABELA DE PRODUTOS]
WHERE [PREÇO DE LISTA] < 6 AND EMBALAGEM = 'LATA';

SELECT * FROM [TABELA DE PRODUTOS]
WHERE EMBALAGEM = 'LATA';

SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE CLIENTES]
WHERE ESTADO <> 'RJ'; 

UPDATE [TABELA DE PRODUTOS] 
SET [PREÇO DE LISTA] = [PREÇO DE LISTA] * 0.9
WHERE EMBALAGEM = 'LATA';

SELECT * FROM [TABELA DE PRODUTOS];

UPDATE [TABELA DE PRODUTOS] 
SET EMBALAGEM = 'GARRAFA', [PREÇO DE LISTA] = 8.10
WHERE [ID PRODUTO] = '1088126';

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [ID PRODUTO] = '1088126';

DELETE FROM [TABELA DE PRODUTOS]
WHERE [ID PRODUTO] = '1004327';