SELECT * FROM [TABELA DE PRODUTOS];

UPDATE [TABELA DE PRODUTOS] SET NOME = UPPER(NOME), EMBALAGEM = UPPER(EMBALAGEM), TAMANHO = UPPER(TAMANHO), SABOR = UPPER(SABOR);

SELECT * FROM [TABELA DE CLIENTES];

SELECT NOME, ESTADO FROM [TABELA DE CLIENTES];

SELECT * FROM [TABELA DE CLIENTES]
ORDER BY NOME;

SELECT * FROM [TABELA DE PRODUTOS]
ORDER BY [PREÇO DE LISTA] ;

UPDATE [TABELA DE PRODUTOS] SET TAMANHO = (SABOR), SABOR = (TAMANHO) WHERE [ID PRODUTO] IN ('1000889', '1004327', '1040107', '1078680', '1088126',
'5449310', '1037797');

/*Estou usando o AS aqui para quando eu quero dar um apelido para a tabela*/
SELECT NOME AS [NOME DO CLIENTE], CEP, ESTADO FROM [TABELA DE CLIENTES];

SELECT NOME AS [NOME DOS VENDEDORES], [PERCENTUAL COMISSÃO] AS [%] FROM [TABELA DE VENDEDORES];

INSERT INTO [TABELA DE VENDEDORES] VALUES 
('4', 'MARIA FERNADA', 7);

UPDATE [TABELA DE VENDEDORES] SET NOME = 'Maria Fernada' WHERE [ID VENDEDORES] = '4';
/*Aqui estou usando o UPDATE junto com WHERE para alterar o nome de de uma só pessoa que eu acabei inserindo de forma errada*/

SELECT DISTINCT SABOR FROM [TABELA DE PRODUTOS];
/*Para quando que quero eliminar valores duplicados da consulta*/