SELECT NOME AS [NOME DO CLIENTE], ESTADO, [PRIMEIRA COMPRA] 
FROM [TABELA DE CLIENTES]
WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [PREÇO DE LISTA] <= 7.00;
/*Caso essa ordenação fosse um valor de texto, ele seguiria a ordem alfabetica*/

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE EMBALAGEM = 'PET';

SELECT * FROM [TABELA DE CLIENTES];

SELECT NOME, [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES] 
WHERE [DATA DE NASCIMENTO] > '1989-12-31';

SELECT NOME, [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES] 
WHERE YEAR ([DATA DE NASCIMENTO]) > '1989';

SELECT NOME, [DATA DE NASCIMENTO] 
FROM [TABELA DE CLIENTES] 
WHERE DAY ([DATA DE NASCIMENTO]) > '10';

SELECT NOME 
FROM [TABELA DE CLIENTES]
WHERE NOME <> 'Erica Carvalho';
/*Eu uso o <> quando eu quero excluir algo
 Ou seja, ela vai retornar desconsiderando todos aqueles que são Erica Carvalho.*/