DECLARE 
	@LIMITE_MIN INT,
	@LIMITE_MAX INT;

DECLARE 
	@NUMl_LINHAS_MAX INT,
	@NUM_LINHAS_ESCRITAS INT;

SET @LIMITE_MIN = 3;
SET @LIMITE_MAX = 30;

SET @NUMl_LINHAS_MAX = 10;
SET @NUM_LINHAS_ESCRITAS = 0;

PRINT 'ENTRANDO NO LOOPING'

WHILE @LIMITE_MIN <= @LIMITE_MAX
	BEGIN
		PRINT @LIMITE_MIN;
		SET @NUM_LINHAS_ESCRITAS = @NUM_LINHAS_ESCRITAS + 1
		IF @NUM_LINHAS_ESCRITAS = @NUMl_LINHAS_MAX
			BEGIN
				PRINT 'SAI DO LOOPING POR CAUSA DO BREAK';
				BREAK;
			END;
		SET @LIMITE_MIN = @LIMITE_MIN + 2;
	END;

PRINT 'SAI DO LOOPING'
