--DECLARE @MATRICULA VARCHAR(5);

--DECLARE  @NOME VARCHAR(100);

--DECLARE @PERCENTUAL FLOAT;

--DECLARE @DATA DATE;

--DECLARE @FERIAS BIT;

--DECLARE @BAIRRO VARCHAR(50);

DECLARE 
	@MATRICULA VARCHAR(5),
	@NOME VARCHAR(100),
	@PERCENTUAL FLOAT,
	@DATA DATE,
	@FERIAS BIT,
	@BAIRRO VARCHAR(50);

DECLARE
	@CLIENTE VARCHAR(10),
	@IDADE INT,
	@DATA_NASCUMENTO DATE,
	@CUSTO FLOAT;