DECLARE	
	@CPF VARCHAR(50),
	@NOME VARCHAR(100),
	@DATA_NASCIMENTO DATE,
	@IDADE INT,
	@SAIDA VARCHAR(500);

SET @CPF = '19290992743';

--1471156710
--19290992743
--2600586709

SELECT 
	@NOME = NOME, 
	@DATA_NASCIMENTO = [DATA DE NASCIMENTO], 
	@IDADE = IDADE 
FROM [TABELA DE CLIENTES]
WHERE CPF = @CPF;

SET @SAIDA = 'O PRIMEIRO NOME DO CLIENTE ' + @NOME + ' CUJO CPF É ' + @CPF + ', CORRESPONDE A: ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME) - 1);

PRINT @SAIDA

--PRINT 'O PRIMEIRO NOME DO CLIENTE ' + @NOME + ' CUJO CPF É ' + @CPF + ', CORRESPONDE A: ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME) - 1);
