SELECT GETDATE() AS DIA_HORA;

SELECT DATENAME(WEEKDAY, GETDATE()) AS DIA_HOJE;

SELECT
	GETDATE() AS DIA_HOJE,
	DATEADD(DAY, 5, GETDATE()) AS MAIS_5_DIAS;

SELECT
	DATENAME(WEEKDAY, GETDATE()) AS DIA_HOJE,
	DATENAME(WEEKDAY, DATEADD(DAY, 5, GETDATE())) AS MAIS_5_DIAS_SEMANA;

--------------------

DECLARE 
	@DIA_SEMANA VARCHAR(20),
	@NUMERO_DIAS INT;

SET @NUMERO_DIAS = 5;
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()));

PRINT @DIA_SEMANA

IF @DIA_SEMANA = 'Saturday' OR @DIA_SEMANA = 'Sunday'
	PRINT 'ESTE DIA É FIM DE SEMANA';
ELSE
	PRINT 'ESTE DIA É DIA DA SEMANA';