DECLARE @CPF VARCHAR(15);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;
DECLARE @IDADE_ANTIGA INT;

SET @CPF = '1471156710';

SELECT 
	@DATA_NASCIMENTO = [DATA DE NASCIMENTO], 
	@IDADE_ANTIGA = IDADE
FROM [TABELA DE CLIENTES] 
WHERE CPF = @CPF;
 
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());

IF @IDADE != @IDADE_ANTIGA
	BEGIN
		UPDATE [TABELA DE CLIENTES] 
		SET IDADE = @IDADE 
		WHERE CPF = @CPF
		PRINT 'IDADE NOVA';
	END;
ELSE
	PRINT 'TU É BURRO PAI?';
