DECLARE @CPF VARCHAR(15);
DECLARE @DATA_NASCIMENTO DATE;
DECLARE @IDADE INT;

SET @CPF = '1471156710';

SELECT 
	@DATA_NASCIMENTO = [DATA DE NASCIMENTO]
FROM [TABELA DE CLIENTES] 
WHERE CPF = @CPF;
 
SET @IDADE = DATEDIFF(YEAR, @DATA_NASCIMENTO, GETDATE());

IF @IDADE != (SELECT IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF)
	BEGIN
		UPDATE [TABELA DE CLIENTES] 
		SET IDADE = @IDADE 
		WHERE CPF = @CPF
		PRINT 'IDADE NOVA';
	END;
ELSE
	PRINT 'TU É BURRO PAI?';
