SELECT * FROM [TABELA DE CLIENTES];

SELECT
	BAIRRO,
	SUM([LIMITE DE CREDITO])
FROM [TABELA DE CLIENTES]
GROUP BY BAIRRO;


SELECT
	SUM([LIMITE DE CREDITO])
FROM [TABELA DE CLIENTES]
WHERE BAIRRO = 'Água Santa'

-------------------------

DECLARE
	@LIMITE_MAX FLOAT,
	@LIMITE_ATUAL FLOAT,
	@BAIRRO VARCHAR(30);

SET @LIMITE_MAX = 500000;

SET @BAIRRO = 'Água Santa';

SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO])
FROM [TABELA DE CLIENTES]
WHERE BAIRRO = @BAIRRO; 

IF @LIMITE_MAX <= @LIMITE_ATUAL
	PRINT 'VALOR PASSOU, BUM';
ELSE
	PRINT 'VALOR NÃO PASSOU, BOMM';

-------------------------

DECLARE
	@LIMITE_MAX FLOAT,
	@BAIRRO VARCHAR(30);

SET @LIMITE_MAX = 500000;

SET @BAIRRO = 'Água Santa';

IF @LIMITE_MAX <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)
	PRINT 'VALOR PASSOU, BUM';
ELSE
	PRINT 'VALOR NÃO PASSOU, BOMM';

