DECLARE 
	@LIMITE_MIN INT,
	@LIMITE_MAX INT;

SET @LIMITE_MIN = 3;
SET @LIMITE_MAX = 30;

PRINT 'ENTRANDO NO LOOPING'

WHILE @LIMITE_MIN <= @LIMITE_MAX
	BEGIN
		PRINT @LIMITE_MIN;
		SET @LIMITE_MIN = @LIMITE_MIN + 2;
	END;

PRINT 'SAI DO LOOPING'
