CREATE TABLE PRODUTOS (
ID_PRODUTOS VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
[PREÇO LISTA] DECIMAL(30,2) NULL,
PRIMARY KEY (ID_PRODUTOS)
);

GO

CREATE TABLE VENDEDORES (
ID_

);

DROP TABLE PRODUTOS;