CREATE TABLE PRODUTOS (
ID VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
[PREÇO LISTA] DECIMAL(30,2) NULL,
PRIMARY KEY (ID)
);