CREATE DATABASE [VENDAS SUCOS];

CREATE DATABASE [VENDAS SUCOS 2]
ON (
NAME = 'VENDAS_SUCOS_2_DAT',
FILENAME = 'C:\TEMP\VENDAS_SUCOS_02.MDF',
SIZE = 10MB,
MAXSIZE = 50MB,
FILEGROWTH = 5MB 
)
LOG ON (
NAME = 'VENDAS_SUCOS_2_LOG',
FILENAME = 'C:\TEMP\VENDAS_SUCOS_02.LDF',
SIZE = 10MB,
MAXSIZE = 50MB,
FILEGROWTH = 5MB 
);