CREATE DATABASE [VENDAS SUCOS 3]
 CONTAINMENT = NONE
 ON  PRIMARY ( 
	NAME = N'VENDAS SUCOS 3', 
	FILENAME = N'C:\temp\VENDAS_SUCOS_03.MDF', 
	SIZE = 10KB, 
	MAXSIZE = 50KB, 
	FILEGROWTH = 10KB )
 LOG ON ( 
	NAME = N'VENDAS SUCOS 3_log', 
	FILENAME = N'C:\temp\VENDAS_SUCOS_03.LDF', 
	SIZE = 10KB, 
	MAXSIZE = 50KB, 
	FILEGROWTH = 10KB )

GO

DROP DATABASE [VENDAS SUCOS 2];

GO