CREATE TABLE TAB_IDENTITY
	(ID INT IDENTITY(1,1) NOT NULL,
	DESCRITOR VARCHAR(20) NULL);

INSERT INTO TAB_IDENTITY 
	VALUES ('CLIENTE X');

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY
	VALUES 
		('CLIENTE Y'),
		('CLIENTE Z');

DELETE TAB_IDENTITY
WHERE ID = 1;

INSERT INTO TAB_IDENTITY
	VALUES
		('CLIENTE A'),
		('CLIENTE B'),
		('CLIENTE C');

DELETE TAB_IDENTITY
WHERE ID = 5;

INSERT INTO TAB_IDENTITY
	VALUES
		('CLIENTE W'),
		('CLIENTE G'),
		('CLIENTE K'),
		('CLIENTE J');

SELECT * FROM TAB_IDENTITY;

SELECT * FROM TAB_IDENTITY
ORDER BY ID;