CREATE TABLE TAB_IDENTITY
	(ID INT IDENTITY(1,1) NOT NULL,
	DESCRITOR VARCHAR(20) NULL);

INSERT INTO TAB_IDENTITY 
	VALUES ('CLIENTE X');

SELECT * FROM TAB_IDENTITY;

INSERT INTO TAB_IDENTITY
	VALUES 
		('CLIENTE Y'),
		('CLIENTE Z');

DELETE TAB_IDENTITY
WHERE ID = 1;

INSERT INTO TAB_IDENTITY
	VALUES
		('CLIENTE A'),
		('CLIENTE B'),
		('CLIENTE C');

DELETE TAB_IDENTITY
WHERE ID = 5;

INSERT INTO TAB_IDENTITY
	VALUES
		('CLIENTE W'),
		('CLIENTE G'),
		('CLIENTE K'),
		('CLIENTE J');

SELECT * FROM TAB_IDENTITY;

SELECT * FROM TAB_IDENTITY
ORDER BY ID;


CREATE TABLE TAB_IDENTITY_2
	(ID INT IDENTITY(100,5) NOT NULL,
	DESCRITOR VARCHAR(20) NULL);

INSERT INTO TAB_IDENTITY_2
	VALUES
		('CLIENTE A'),
		('CLIENTE B'),
		('CLIENTE C');

SELECT * FROM TAB_IDENTITY_2;

--INSERT INTO TAB_IDENTITY (ID, DESCRITOR)
--	VALUES
--		(255, 'CLIENTE W');

--Por padrão eu não posso interferir no campo do tipo IDENTITY