UPDATE SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS
SET PRECO_DE_LISTA = PRECO_DE_LISTA * 1.2;

SELECT 
	A.ID_PRODUTOS AS ID_MINHA_TABELA,
	A.PRECO_LISTA AS PRECO_LISTA_MINHA_TABELA,
	B.CODIGO_DO_PRODUTO AS COD_APOIO,
	B.PRECO_DE_LISTA AS PRECO_LISTA_APOIO
FROM PRODUTOS A
INNER JOIN SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS B
ON A.ID_PRODUTOS = B.CODIGO_DO_PRODUTO;

-------------------------------

--UPDATE A 
--SET A.PRECO_LISTA = B.PRECO_DE_LISTA
--FROM PRODUTOS A
--INNER JOIN SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS B
--ON A.ID_PRODUTOS = B.CODIGO_DO_PRODUTO;

--Os dois comandos tem o mesmo resultado final, mas o MERGE foi feito para que você pegue dados de uma tabela e traga para outra tabela 

MERGE INTO PRODUTOS A 
USING SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS B
ON A.ID_PRODUTOS = B.CODIGO_DO_PRODUTO
WHEN MATCHED THEN
UPDATE SET A.PRECO_LISTA = B.PRECO_DE_LISTA;

-------------------------------