SELECT * FROM SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS;

SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, SABOR, TAMANHO, EMBALAGEM, PRECO_DE_LISTA
FROM SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS;

SELECT 
	CODIGO_DO_PRODUTO AS ID_PRODUTOS, 
	NOME_DO_PRODUTO AS DESCRITOR, 
	SABOR, 
	TAMANHO, 
	EMBALAGEM, 
	PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS;

INSERT INTO PRODUTOS
	SELECT 
	CODIGO_DO_PRODUTO AS ID_PRODUTOS, 
	NOME_DO_PRODUTO AS DESCRITOR, 
	SABOR, 
	TAMANHO, 
	EMBALAGEM, 
	PRECO_DE_LISTA AS PRECO_LISTA
FROM SUCOS_FRUTAS.dbo.TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO <> '1040107';

SELECT * FROM PRODUTOS;

SELECT * FROM CLIENTES;

SELECT * FROM SUCOS_FRUTAS.dbo.TABELA_DE_CLIENTES;

SELECT
	CPF,
	NOME,
	ENDERECO_1 AS ENDERECO,
	BAIRRO,
	CIDADE,
	ESTADO,
	CEP,
	DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
	IDADE,
	GENERO,
	LIMITE_DE_CREDITO AS LIMITE_CREDITO,
	VOLUME_DE_COMPRA AS VOLUME_COMPRA,
	PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.dbo.TABELA_DE_CLIENTES;

INSERT INTO CLIENTES
	SELECT
	CPF,
	NOME,
	ENDERECO_1 AS ENDERECO,
	BAIRRO,
	CIDADE,
	ESTADO,
	CEP,
	DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
	IDADE,
	GENERO,
	LIMITE_DE_CREDITO AS LIMITE_CREDITO,
	VOLUME_DE_COMPRA AS VOLUME_COMPRA,
	PRIMEIRA_COMPRA
FROM SUCOS_FRUTAS.dbo.TABELA_DE_CLIENTES
WHERE CPF <> '19290992743';

