SELECT
	CPF, 
	IDADE,
	DATA_NASCIMENTO,
	DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) 
FROM CLIENTES;

SELECT * FROM CLIENTES;

CREATE TRIGGER TG_CLIENTES_IDADE
ON CLIENTES
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
	UPDATE CLIENTES SET IDADE =
	DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) 
END;