/*Não repete as linhas, mostra as linhas distintas/diferentes*/

SELECT * FROM TABELA_DE_CLIENTES;

SELECT DISTINCT BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;
/*Quando eu uso o DISTINCT desse jeito, ele vai pegar os arquivos distintos nas duas colunas que estão acima, ou seja, o que é diferente tanto no bairro quando na cidade*/

SELECT DISTINCT CIDADE, BAIRRO FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = ('Maca') ;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Maca' ;
--Quando eu não coloco % no LIKE, ele funciona como um = só que para texto

SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;
--Assim eu vou ver as combinações diferentes para ambos os campos

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_CLIENTES;

SELECT TOP 7 * FROM TABELA_DE_CLIENTES;
/*Usando o TOP desssa ele vai me mostrar os 7 primeiros resgistros da tabela*/

SELECT TOP 7 * FROM TABELA_DE_CLIENTES;

SELECT TOP 5 * FROM TABELA_DE_CLIENTES WHERE ESTADO = 'SP';

SELECT * FROM NOTAS_FISCAIS;

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-10-01';

--ASC - Do menos pro maior. DESC - Do maior pro menor. O ASC é o padrão do ORDER BY.

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO DESC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS 
ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';

SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT TOP 10 * FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = 1101035
ORDER BY QUANTIDADE DESC;

