SELECT CONVERT(VARCHAR(10), GETDATE(), 121);

SELECT CONVERT(VARCHAR(30), GETDATE(), 121);
--Data para texto

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(30), DATA_DE_NASCIMENTO, 101) 
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA
FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', PRECO_DE_LISTA) as [PREÇO]
FROM TABELA_DE_PRODUTOS;