SELECT CONVERT(VARCHAR(10), GETDATE(), 121);

SELECT CONVERT(VARCHAR(30), GETDATE(), 121);
--Data para texto

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(30), DATA_DE_NASCIMENTO, 101) 
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA
FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', PRECO_DE_LISTA) as [PREÇO]
FROM TABELA_DE_PRODUTOS;
--Conversão implícita

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', CAST(PRECO_DE_LISTA AS VARCHAR(10))) as [PREÇO]
FROM TABELA_DE_PRODUTOS;
--Conversão explicita

-------------

--Queremos construir um SQL cujo resultado seja para cada cliente:

--"O cliente João da Silva comprou R$ 121222,12 no ano de 2016".

--Faça isso somente para o ano de 2016.

SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM NOTAS_FISCAIS;

SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT NOME, QUANTIDADE, PRECO, DATA_VENDA
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO;