/*Com o COUNT eu estou contando o número de linhas de uma tabela*/
SELECT COUNT (*) FROM TABELA_DE_CLIENTES;
SELECT COUNT (*) FROM TABELA_DE_PRODUTOS;
SELECT COUNT (*) FROM TABELA_DE_CLIENTES;
SELECT COUNT (*) FROM NOTAS_FISCAIS;
SELECT COUNT (*) FROM ITENS_NOTAS_FISCAIS;

