--DENTRO DE UM MÊS, QUAIS FORAM OS CLIENTES QUE COMPRARAM MAIS DO QUE O VOLUME DE COMPRA

SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM NOTAS_FISCAIS;

SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT TC.NOME, TC.VOLUME_DE_COMPRA, NF.DATA_VENDA, INF.QUANTIDADE, INF.PRECO
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
ORDER BY TC.NOME;

SELECT TC.NOME, FLOOR(SUM(INF.PRECO)) AS [PREÇO], TC.VOLUME_DE_COMPRA, MONTH(NF.DATA_VENDA) AS [MÊS]
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_CLIENTES TC
ON NF.CPF = TC.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY TC.NOME, MONTH(NF.DATA_VENDA), TC.VOLUME_DE_COMPRA
HAVING FLOOR(SUM(INF.PRECO)) > TC.VOLUME_DE_COMPRA
ORDER BY TC.NOME;
