SELECT * FROM TABELA_DE_CLIENTES;

SELECT NOME, LOWER(NOME) AS [NOME MINUSCULO], UPPER(NOME) AS [NOME MAIUSCULO]
FROM TABELA_DE_CLIENTES;

SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO, '-', CEP) AS [ENDEREÇO COMPLETO]
FROM TABELA_DE_CLIENTES;

--Eu posso juntar as informações dessas duas formas, como no exemplo acima e como no exemplo abaixo.

SELECT NOME, ENDERECO_1+ ' '+ BAIRRO+ ' '+ CIDADE+ ' '+ ESTADO+ '-'+ CEP AS [ENDEREÇO COMPLETO]
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, LEFT(NOME_DO_PRODUTO, 5) AS [OS 5 PRIMEIROS CHAR]
FROM TABELA_DE_PRODUTOS;

SELECT TAMANHO, REPLACE((REPLACE(TAMANHO, 'Litros', 'L')),'Litro', 'L') AS [TAMANHO MODIFICADO]
FROM TABELA_DE_PRODUTOS;