SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;

SELECT CIDADE, SUM(IDADE) AS IDADE 
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE
--O grupo que está sendo somado não entra, caso contrario aconteceria como no exemplo abaixo
ORDER BY CIDADE, IDADE;

--SELECT CIDADE, SUM(IDADE) AS IDADE 
--FROM TABELA_DE_CLIENTES
--GROUP BY CIDADE, IDADE
--ORDER BY CIDADE, IDADE;

SELECT CIDADE, SUM(IDADE) AS IDADE, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT CIDADE, AVG(IDADE) AS IDADE, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT CIDADE, COUNT(*) AS [NÚMERO DE CLIENTES] 
FROM TABELA_DE_CLIENTES 
GROUP BY CIDADE;
--Essa função COUNT, vai estar contando o número de linhas que são agrupadas usando um determinado criterio, nesse caso seria CIDADE

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, COUNT(*) AS [PRODUTOS POR EMBALAGEM] 
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS [PRODUTOS POR EMBALAGEM] 
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM;