SELECT * FROM TABELA_DE_CLIENTES;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 900000;
--O HAVING serve para quando eu quero usar campos com funções de agregação, com o SUM, pq no WHERE eu só posso colocar campos da tabela

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS [PRECO MAX], MIN(PRECO_DE_LISTA) AS [PRECO MIN]
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS [PRECO MAX], MIN(PRECO_DE_LISTA) AS [PRECO MIN]
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >= 10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) > 20;