
SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS [NOTAS FISCAIS]
FROM NOTAS_FISCAIS
GROUP BY MATRICULA;

SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*) AS [NOTAS FISCAIS]
FROM NOTAS_FISCAIS
INNER JOIN TABELA_DE_VENDEDORES
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;

--SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS [NOTAS FISCAIS]
--FROM NOTAS_FISCAIS NF
--INNER JOIN TABELA_DE_VENDEDORES TV
--ON NF.MATRICULA = TV.MATRICULA
--GROUP BY NF.MATRICULA, TV.NOME;

SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS [NOTAS FISCAIS]
FROM TABELA_DE_VENDEDORES TV
INNER JOIN NOTAS_FISCAIS NF
ON NF.MATRICULA = TV.MATRICULA
GROUP BY NF.MATRICULA, TV.NOME;
