SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS [NOTAS FISCAIS]
FROM NOTAS_FISCAIS
GROUP BY MATRICULA;

SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*) AS [NOTAS FISCAIS]
FROM NOTAS_FISCAIS
INNER JOIN TABELA_DE_VENDEDORES
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;

--SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS [NOTAS FISCAIS]
--FROM NOTAS_FISCAIS NF
--INNER JOIN TABELA_DE_VENDEDORES TV
--ON NF.MATRICULA = TV.MATRICULA
--GROUP BY NF.MATRICULA, TV.NOME;

SELECT NF.MATRICULA, TV.NOME, COUNT(*) AS [NOTAS FISCAIS]
FROM TABELA_DE_VENDEDORES TV
INNER JOIN NOTAS_FISCAIS NF
ON NF.MATRICULA = TV.MATRICULA
GROUP BY NF.MATRICULA, TV.NOME;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;

SELECT ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS 
INNER JOIN TABELA_DE_PRODUTOS
ON ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO = TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO
GROUP BY ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;

--SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
--FROM ITENS_NOTAS_FISCAIS  INF
--INNER JOIN TABELA_DE_PRODUTOS TP 
--ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
--GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
--HAVING SUM(INF.QUANTIDADE) > 394000 
--ORDER BY SUM(INF.QUANTIDADE) DESC;