SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_VENDEDORES;

SELECT 
	TV.NOME AS [NOME DO VENDEDOR],
	TV.BAIRRO AS [BAIRRO VENDEDORES],
	TC.NOME AS [NOME DO CLIENTE],
	TC.BAIRRO AS [BAIRRO CLIENTES]
FROM TABELA_DE_VENDEDORES TV
FULL JOIN TABELA_DE_CLIENTES TC
ON TV.BAIRRO = TC.BAIRRO;

SELECT DISTINCT
	TV.NOME AS [NOME DO VENDEDOR],
	TV.BAIRRO AS [BAIRRO VENDEDORES],
	TC.NOME AS [NOME DO CLIENTE],
	TC.BAIRRO AS [BAIRRO CLIENTES]
FROM TABELA_DE_VENDEDORES TV
INNER JOIN TABELA_DE_CLIENTES TC
ON TV.BAIRRO = TC.BAIRRO;

SELECT COUNT(*) AS [TOTAL CLIENTES]
FROM TABELA_DE_CLIENTES;
--16

SELECT COUNT(*) AS [TOTAL VENDEDORES]
FROM TABELA_DE_VENDEDORES;
--4