SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_VENDEDORES;

SELECT 
	TV.BAIRRO AS [BAIRRO VENDEDORES],
	TC.BAIRRO AS [BAIRRO CLIENTES]
FROM TABELA_DE_VENDEDORES TV
FULL JOIN TABELA_DE_CLIENTES TC
ON TV.BAIRRO = TC.BAIRRO;

SELECT 
	TV.BAIRRO AS [BAIRRO VENDEDORES],
	TC.BAIRRO AS [BAIRRO CLIENTES]
FROM TABELA_DE_VENDEDORES TV
INNER JOIN TABELA_DE_CLIENTES TC
ON TV.BAIRRO = TC.BAIRRO;