SELECT * FROM TABELA_DE_CLIENTES;

SELECT DISTINCT
	TC.CPF AS [CPF DO CADASTRO],
	TC.NOME AS [NOME DO CLIENTE],
	NF.CPF AS [CPF DA NOTA]
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF;

SELECT COUNT(*) AS CLIENTE
FROM TABELA_DE_CLIENTES;
--Como eu não tenho nenhum campo a ser agrupado eu não devo usar o GROUP BY, mas caso tivesse, eu teria que usar

INSERT INTO TABELA_DE_CLIENTES
VALUES(
'45862334875',
'Dori Thor',
'R.Sla',
NULL,
'Parque S',
'São Paulo',
'SP',
'86423121',
'1996-12-18',
33,
'F',
180000, 
240000,
0
);

SELECT COUNT(*) AS CLIENTE
FROM TABELA_DE_CLIENTES;

SELECT DISTINCT
	TC.CPF AS [CPF DO CADASTRO],
	TC.NOME AS [NOME DO CLIENTE],
	NF.CPF AS [CPF DA NOTA]
FROM TABELA_DE_CLIENTES TC
LEFT JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF;

SELECT DISTINCT
	TC.CPF AS [CPF DO CADASTRO],
	TC.NOME AS [NOME DO CLIENTE]
FROM TABELA_DE_CLIENTES TC
LEFT JOIN NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
WHERE NF.CPF IS NULL;