SELECT DISTINCT BAIRRO
FROM TABELA_DE_CLIENTES;

SELECT DISTINCT BAIRRO
FROM TABELA_DE_VENDEDORES;

SELECT BAIRRO
FROM TABELA_DE_CLIENTES
UNION
SELECT BAIRRO
FROM TABELA_DE_CLIENTES;

SELECT BAIRRO
FROM TABELA_DE_CLIENTES
UNION ALL
SELECT BAIRRO
FROM TABELA_DE_CLIENTES;