CREATE VIEW MEDIA_EMBALAGEM AS 
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS [PREÇO MEDIO P/ EMBALAGEM]
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;
GO

SELECT * FROM MEDIA_EMBALAGEM;
GO

SELECT MEDIA_EMBALAGEM.EMBALAGEM, MEDIA_EMBALAGEM.[PREÇO MEDIO P/ EMBALAGEM]
FROM (
		SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS [PREÇO MEDIO P/ EMBALAGEM]
		FROM TABELA_DE_PRODUTOS
		GROUP BY EMBALAGEM
	) AS MEDIA_EMBALAGEM
WHERE MEDIA_EMBALAGEM.[PREÇO MEDIO P/ EMBALAGEM] <= 10
ORDER BY MEDIA_EMBALAGEM.[PREÇO MEDIO P/ EMBALAGEM];
GO

SELECT EMBALAGEM, [PREÇO MEDIO P/ EMBALAGEM]
FROM MEDIA_EMBALAGEM
WHERE [PREÇO MEDIO P/ EMBALAGEM] <= 10;
GO

CREATE VIEW SOMA_QUANTIDADE AS
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO;
GO

SELECT * FROM SOMA_QUANTIDADE;

SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, QUANTIDADE
FROM SOMA_QUANTIDADE
WHERE QUANTIDADE > 394000
ORDER BY QUANTIDADE DESC;
