CREATE VIEW MEDIA_EMBALAGEM AS 
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS [PREÇO MEDIO P/ EMBALAGEM]
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT * FROM MEDIA_EMBALAGEM;

SELECT MEDIA_EMBALAGEM.EMBALAGEM, MEDIA_EMBALAGEM.[PREÇO MEDIO P/ EMBALAGEM]
FROM (
		SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS [PREÇO MEDIO P/ EMBALAGEM]
		FROM TABELA_DE_PRODUTOS
		GROUP BY EMBALAGEM
	) AS MEDIA_EMBALAGEM
WHERE MEDIA_EMBALAGEM.[PREÇO MEDIO P/ EMBALAGEM] <= 10
ORDER BY MEDIA_EMBALAGEM.[PREÇO MEDIO P/ EMBALAGEM];

SELECT EMBALAGEM, [PREÇO MEDIO P/ EMBALAGEM]
FROM MEDIA_EMBALAGEM
WHERE [PREÇO MEDIO P/ EMBALAGEM] <= 10;
